[general]
import = ["~/.config/alacritty/catthode.toml"]

[window]
decorations = "none"
opacity = 0.75
startup_mode = "Maximized"

[font]
size = 16.0

[font.normal]
family = "CaskaydiaMono Nerd Font Mono"
style = "Regular"

[font.bold]
family = "CaskaydiaMono Nerd Font Mono"
style = "Bold"

[font.italic]
family = "CaskaydiaMono Nerd Font Mono"
style = "Italic"

[font.bold_italic]
family = "CaskaydiaMono Nerd Font Mono"
style = "Bold Italic"

[keyboard]
bindings = [{ key = "Return", mods = "Shift", chars = "\n" }]
