# ======================================================================================
# Catthode Color Customizations - Warm-Focused Theme
#
# Color Palette:
# Surface:   Base #000000, Sidebar #141414, Selection #2d2d2d, Border #636363
# Phosphor:  Text #ffffff, Variable #e8e8e8, Comment #b3b3b3, Ignored #757575
# WARM:      Wheat #fae2c8, Tan #d9b98c, Gold #ffb86c, Amber #ff9e3b, Clay #f08d49, Red #ff6b6b
# COOL:      Green #b9d665, Cyan #aee6d6, Blue #9cd9e6, Purple #eba4be
# ======================================================================================

# Global/General
typeset -g POWERLEVEL9K_BACKGROUND='#000000'
typeset -g POWERLEVEL9K_RULER_FOREGROUND='#636363'
typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_FOREGROUND='#636363'
typeset -g POWERLEVEL9K_OS_ICON_FOREGROUND='#ff9e3b'

# Directory
typeset -g POWERLEVEL9K_DIR_PATH_ABSOLUTE=true
typeset -g POWERLEVEL9K_DIR_DEFAULT_FOREGROUND='#d9b98c'
typeset -g POWERLEVEL9K_DIR_DEFAULT_BACKGROUND='#000000'
typeset -g POWERLEVEL9K_DIR_HOME_FOREGROUND='#ffffff'
typeset -g POWERLEVEL9K_DIR_HOME_BACKGROUND='#000000'
typeset -g POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND='#ffffff'
typeset -g POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND='#000000'
typeset -g POWERLEVEL9K_DIR_NOT_WRITABLE_FOREGROUND='#ffffff'
typeset -g POWERLEVEL9K_DIR_NOT_WRITABLE_BACKGROUND='#000000'
typeset -g POWERLEVEL9K_DIR_ETC_FOREGROUND='#ffffff'
typeset -g POWERLEVEL9K_DIR_ETC_BACKGROUND='#000000'
typeset -g POWERLEVEL9K_DIR_FOREGROUND='#d9b98c'
typeset -g POWERLEVEL9K_DIR_BACKGROUND='#000000'
typeset -g POWERLEVEL9K_DIR_PATH_SEPARATOR_FOREGROUND='#ff9e3b'
typeset -g POWERLEVEL9K_DIR_PATH_SEPARATOR_BACKGROUND='#000000'
typeset -g POWERLEVEL9K_DIR_PATH_HIGHLIGHT_FOREGROUND='#ff9e3b'
typeset -g POWERLEVEL9K_DIR_PATH_HIGHLIGHT_BACKGROUND='#000000'
typeset -g POWERLEVEL9K_DIR_SHORTENED_FOREGROUND='#e8e8e8'
typeset -g POWERLEVEL9K_DIR_ANCHOR_FOREGROUND='#fae2c8'

# Git/VCS
typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND='#d9b98c'
typeset -g POWERLEVEL9K_VCS_CLEAN_BACKGROUND='#000000'
typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='#ff6b6b'
typeset -g POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='#000000'
typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND='#ff6b6b'
typeset -g POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND='#000000'
typeset -g POWERLEVEL9K_VCS_VISUAL_IDENTIFIER_COLOR='#d9b98c'
typeset -g POWERLEVEL9K_VCS_LOADING_VISUAL_IDENTIFIER_COLOR='#757575'

# Status
typeset -g POWERLEVEL9K_STATUS_OK_FOREGROUND='#b9d665'
typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND='#ff6b6b'
typeset -g POWERLEVEL9K_STATUS_OK_PIPE_FOREGROUND='#ffb86c'
typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL_FOREGROUND='#ff6b6b'
typeset -g POWERLEVEL9K_STATUS_ERROR_PIPE_FOREGROUND='#ff6b6b'

# Prompt Character
typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND='#ff9e3b'
typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND='#ff6b6b'

# Time
typeset -g POWERLEVEL9K_TIME_FOREGROUND='#b3b3b3'

# Command Execution
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND='#ffb86c'
typeset -g POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND='#ff9e3b'

# Environment Tools
typeset -g POWERLEVEL9K_DIRENV_FOREGROUND='#ff9e3b'
typeset -g POWERLEVEL9K_ASDF_FOREGROUND='#ffb86c'
typeset -g POWERLEVEL9K_NORDVPN_FOREGROUND='#aee6d6'
typeset -g POWERLEVEL9K_RANGER_FOREGROUND='#f08d49'
typeset -g POWERLEVEL9K_NNN_FOREGROUND='#f08d49'
typeset -g POWERLEVEL9K_LF_FOREGROUND='#f08d49'
typeset -g POWERLEVEL9K_XPLR_FOREGROUND='#f08d49'
typeset -g POWERLEVEL9K_VIM_SHELL_FOREGROUND='#ff6b6b'
typeset -g POWERLEVEL9K_MIDNIGHT_COMMANDER_FOREGROUND='#f08d49'
typeset -g POWERLEVEL9K_NIX_SHELL_FOREGROUND='#9cd9e6'

# System Resources
typeset -g POWERLEVEL9K_DISK_USAGE_NORMAL_FOREGROUND='#ffb86c'
typeset -g POWERLEVEL9K_DISK_USAGE_WARNING_FOREGROUND='#ff9e3b'
typeset -g POWERLEVEL9K_DISK_USAGE_CRITICAL_FOREGROUND='#ff6b6b'
typeset -g POWERLEVEL9K_RAM_FOREGROUND='#d9b98c'
typeset -g POWERLEVEL9K_SWAP_FOREGROUND='#f08d49'
typeset -g POWERLEVEL9K_LOAD_NORMAL_FOREGROUND='#ffb86c'
typeset -g POWERLEVEL9K_LOAD_WARNING_FOREGROUND='#ff9e3b'
typeset -g POWERLEVEL9K_LOAD_CRITICAL_FOREGROUND='#ff6b6b'

# Task Management
typeset -g POWERLEVEL9K_TODO_FOREGROUND='#ffb86c'
typeset -g POWERLEVEL9K_TIMEWARRIOR_FOREGROUND='#ff9e3b'
typeset -g POWERLEVEL9K_TASKWARRIOR_FOREGROUND='#f08d49'

# System Info
typeset -g POWERLEVEL9K_CPU_ARCH_FOREGROUND='#fae2c8'
typeset -g POWERLEVEL9K_CONTEXT_ROOT_FOREGROUND='#ff6b6b'
typeset -g POWERLEVEL9K_CONTEXT_{REMOTE,REMOTE_SUDO}_FOREGROUND='#ff9e3b'
typeset -g POWERLEVEL9K_CONTEXT_FOREGROUND='#d9b98c'

# Python Environment Managers
typeset -g POWERLEVEL9K_VIRTUALENV_FOREGROUND='#ffb86c'
typeset -g POWERLEVEL9K_ANACONDA_FOREGROUND='#f08d49'
typeset -g POWERLEVEL9K_PYENV_FOREGROUND='#ff9e3b'

# Language Environment Managers
typeset -g POWERLEVEL9K_GOENV_FOREGROUND='#aee6d6'
typeset -g POWERLEVEL9K_NODENV_FOREGROUND='#b9d665'
typeset -g POWERLEVEL9K_NVM_FOREGROUND='#b9d665'
typeset -g POWERLEVEL9K_NODEENV_FOREGROUND='#b9d665'
typeset -g POWERLEVEL9K_RBENV_FOREGROUND='#ff6b6b'
typeset -g POWERLEVEL9K_RVM_FOREGROUND='#ff6b6b'
typeset -g POWERLEVEL9K_FVM_FOREGROUND='#9cd9e6'
typeset -g POWERLEVEL9K_LUAENV_FOREGROUND='#d9b98c'
typeset -g POWERLEVEL9K_JENV_FOREGROUND='#f08d49'
typeset -g POWERLEVEL9K_PLENV_FOREGROUND='#eba4be'
typeset -g POWERLEVEL9K_PERLBREW_FOREGROUND='#eba4be'
typeset -g POWERLEVEL9K_PHPENV_FOREGROUND='#eba4be'
typeset -g POWERLEVEL9K_SCALAENV_FOREGROUND='#ff6b6b'
typeset -g POWERLEVEL9K_HASKELL_STACK_FOREGROUND='#eba4be'

# Language Version Indicators
typeset -g POWERLEVEL9K_NODE_VERSION_FOREGROUND='#b9d665'
typeset -g POWERLEVEL9K_GO_VERSION_FOREGROUND='#aee6d6'
typeset -g POWERLEVEL9K_RUST_VERSION_FOREGROUND='#f08d49'
typeset -g POWERLEVEL9K_DOTNET_VERSION_FOREGROUND='#eba4be'
typeset -g POWERLEVEL9K_PHP_VERSION_FOREGROUND='#eba4be'
typeset -g POWERLEVEL9K_LARAVEL_VERSION_FOREGROUND='#ff6b6b'
typeset -g POWERLEVEL9K_JAVA_VERSION_FOREGROUND='#f08d49'
typeset -g POWERLEVEL9K_PACKAGE_FOREGROUND='#ffb86c'

# ASDF Language-Specific Colors
typeset -g POWERLEVEL9K_ASDF_RUBY_FOREGROUND='#ff6b6b'
typeset -g POWERLEVEL9K_ASDF_PYTHON_FOREGROUND='#ffb86c'
typeset -g POWERLEVEL9K_ASDF_GOLANG_FOREGROUND='#aee6d6'
typeset -g POWERLEVEL9K_ASDF_NODEJS_FOREGROUND='#b9d665'
typeset -g POWERLEVEL9K_ASDF_RUST_FOREGROUND='#f08d49'
typeset -g POWERLEVEL9K_ASDF_DOTNET_CORE_FOREGROUND='#eba4be'
typeset -g POWERLEVEL9K_ASDF_FLUTTER_FOREGROUND='#9cd9e6'
typeset -g POWERLEVEL9K_ASDF_LUA_FOREGROUND='#d9b98c'
typeset -g POWERLEVEL9K_ASDF_JAVA_FOREGROUND='#f08d49'
typeset -g POWERLEVEL9K_ASDF_PERL_FOREGROUND='#eba4be'
typeset -g POWERLEVEL9K_ASDF_ERLANG_FOREGROUND='#ff6b6b'
typeset -g POWERLEVEL9K_ASDF_ELIXIR_FOREGROUND='#eba4be'
typeset -g POWERLEVEL9K_ASDF_POSTGRES_FOREGROUND='#9cd9e6'
typeset -g POWERLEVEL9K_ASDF_PHP_FOREGROUND='#eba4be'
typeset -g POWERLEVEL9K_ASDF_HASKELL_FOREGROUND='#eba4be'
typeset -g POWERLEVEL9K_ASDF_JULIA_FOREGROUND='#b9d665'

# Cloud & Infrastructure
typeset -g POWERLEVEL9K_KUBECONTEXT_DEFAULT_FOREGROUND='#9cd9e6'
typeset -g POWERLEVEL9K_TERRAFORM_OTHER_FOREGROUND='#eba4be'
typeset -g POWERLEVEL9K_TERRAFORM_VERSION_FOREGROUND='#eba4be'
typeset -g POWERLEVEL9K_AWS_DEFAULT_FOREGROUND='#ff9e3b'
typeset -g POWERLEVEL9K_AWS_EB_ENV_FOREGROUND='#f08d49'
typeset -g POWERLEVEL9K_AZURE_FOREGROUND='#9cd9e6'
typeset -g POWERLEVEL9K_GCLOUD_FOREGROUND='#ffb86c'
typeset -g POWERLEVEL9K_GOOGLE_APP_CRED_DEFAULT_FOREGROUND='#ffb86c'
typeset -g POWERLEVEL9K_TOOLBOX_FOREGROUND='#f08d49'

# Network & Connectivity
typeset -g POWERLEVEL9K_PUBLIC_IP_FOREGROUND='#d9b98c'
typeset -g POWERLEVEL9K_VPN_IP_FOREGROUND='#aee6d6'
typeset -g POWERLEVEL9K_IP_FOREGROUND='#d9b98c'
typeset -g POWERLEVEL9K_PROXY_FOREGROUND='#aee6d6'
typeset -g POWERLEVEL9K_WIFI_FOREGROUND='#aee6d6'

# Battery
typeset -g POWERLEVEL9K_BATTERY_LOW_FOREGROUND='#ff6b6b'
typeset -g POWERLEVEL9K_BATTERY_{CHARGING,CHARGED}_FOREGROUND='#ffb86c'
typeset -g POWERLEVEL9K_BATTERY_DISCONNECTED_FOREGROUND='#ff9e3b'
